//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lr_Num_2.Resourses.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKER
    {
        public int WorkerID { get; set; }
        public string SurnameInitial { get; set; }
        public string Post { get; set; }
        public Nullable<int> ExperienceYears { get; set; }
    }
}
